name: "Check lints and language"

on:
  push:
    paths:
      - 'draft-*.md'
  pull_request:
    paths:
      - 'draft-*.md'

jobs:
  build:
    name: "Check lints and language"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Languagetool"
        uses: reviewdog/action-languagetool@v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          patterns: "draft-*.md"
