name: "Check lints and language"

on:
  push:
    paths:
      - 'draft-*.md'
  pull_request:
    paths:
      - 'draft-*.md'

jobs:
  build:
    name: "Check lints and language"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Suggest fixes from languagetool"
        uses: reviewdog/action-languagetool@v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          patterns: "draft-*.md"

      # XXX(RLB): This doesn't seem to actually run `make fix-lint`
      #- name: "Fix I-D lints"
      #  uses: martinthomson/i-d-template@v1
      #  with:
      #    token: ${{ github.token }}
      #    input: 'fix-lint'
      
      # XXX(RLB): This reports a bunch of errors, but also fails the CI job.
      #- name: "Fix Markdown lints"
      #  uses: DavidAnson/markdownlint-cli2-action@v15
      #  with:
      #    fix: true
      #    globs: 'draft-*.md'
      
      # No need for this one until the above are fixed
      #- name: "Propose the lint fixes on the PR"
      #  uses: parkerbxyz/suggest-changes@v1
      #  with:
      #    comment: 'Please commit the suggested changes.'
      #    event: 'REQUEST_CHANGES'

